# PNM specific configs
[profile.default]

# How many reports to be found before considering it's a pass test.
# Range: [1, 100]
# Default is 1
report_limit = 10

# How many seconds to run before considering it's a pass test.
# Range: [10, 3600] // 10s to 1h
# Default is 15 min
time_limit = 900
